name: Playwright Tests
on: 
  push: 
    branches: [ main ]  
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    container:
        image: mcr.microsoft.com/playwright:v1.45.3-jammy
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v2 
    - name: Run tests
      run: |
        echo "Install dependencies from lockfile"
        npm ci
        echo "Run playwright tests"
        npm run test:ci